- CONTRIBUTING.md
- README.md
Added lifecycle, license to readme and contribution file
> License, contribution.md and lifecycle badge

- .eslintignore
- LICENSE
Minor fixes for the styling and dev tools. Added license information as well as an eslintignore.
Should partially resolve https://deloittedigital.atlassian.net/jira/software/projects/BVPS/boards/535?selectedIssue=BVPS-54
> BVPS-54: Styling and dev tools

- assets/svgs/LocationDot.jsx
- components/Address Card/AddressCard.jsx
- components/Address Card/AddressCard.module.css
- components/Address Card/AddressCard.stories.jsx
- components/Address Card/AddressCard.test.jsx
- components/Address Card/index.jsx
- pages/index.js
PR for BVPS-177: https://deloittedigital.atlassian.net/browse/BVPS-177
> Address Card Component for Search Results Page

- pages/testPage.js
Adding Search Results component to test page to test that API call is working as expected when deployed in openshift.
> Adding Search Results component to test page to test in dev

- Dockerfile
Adding in env variables to dockerfile temporarily to see if this fixes openshift issues
> Adding in variables to Dockerfile

- components/Footer/Footer.module.css
- components/Footer/index.jsx
- components/Header/Header.jsx
- components/Header/Header.module.css
- components/Navigation/Navigation.jsx
- components/Navigation/Navigation.module.css
- components/Property/PropertyDetails/PropertyDetails.jsx
- components/Property/PropertyDetails/PropertyDetails.module.css
- components/Property/PropertyLayout/PropertyLayout.jsx
- components/Property/PropertyLayout/PropertyLayout.module.css
- components/Property/PropertyOwner/PropertyOwner.jsx
- components/Property/PropertyOwner/PropertyOwner.module.css
- components/Property/PropertySearchHeader/PropertySearchHeader.module.css
- components/Search Results/SearchResults.module.css
- styles/globals.css
[BVPS-226](https://deloittedigital.atlassian.net/browse/BVPS-226)
css change for tablet view and different screen size
> Bvps 226 style change different size

- components/Property/ExpirePINModal/ExpirePINModal.jsx
- components/Property/PropertyOwner/PropertyOwner.jsx
- components/Property/RegeneratePINModal/RegeneratePINModal.jsx
- components/Property/ViewPINHistory/ViewPINHistory.jsx
- content.json
[BVPS-218](https://deloittedigital.atlassian.net/browse/BVPS-218)
1. regenerate pin api changed according to BC latest PR although its not merged yet
2. expire pin api call change: move the unused params and move the typeCode to Content.json
> regenrate & expire pin api call change

- components/Property/ExpirePINModal/ExpirePINModal.jsx
- components/Property/PropertyDetails/PropertyDetails.jsx
- components/Property/PropertyDetails/PropertyDetails.module.css
- components/Property/PropertyLayout/PropertyLayout.jsx
- components/Property/PropertyLayout/PropertyLayout.module.css
- components/Property/PropertySearch/PropertySearch.jsx
- components/Property/PropertyTitleDetails/PropertyTitleDetails.jsx
- components/Property/ViewPINModal/ViewPINModal.jsx
- components/Search Results/SearchResults.jsx
[BVPS-227](https://deloittedigital.atlassian.net/browse/BVPS-227)
Property details connect to api
> Bvps 227 property detail

- components/Address Card/AddressCard.module.css
- components/Property/PropertyDetails/PropertyDetails.module.css
- components/Property/PropertyLayout/PropertyLayout.jsx
- components/Property/PropertyLayout/PropertyLayout.module.css
- components/Search Results/SearchResults.jsx
- components/Search Results/searchResults.stories.jsx
https://deloittedigital.atlassian.net/browse/BVPS-269
https://deloittedigital.atlassian.net/browse/BVPS-270
> BVPS-269 & BVPS-270 - PIN Management Page Bug Fixes

- components/Property/PropertyDetails/PropertyDetails.jsx
- components/Property/PropertyDetails/PropertyDetails.module.css
- components/Property/PropertyLayout/PropertyLayout.jsx
- components/Property/PropertyLayout/PropertyLayout.module.css
- components/Property/PropertySearch/Autocomplete/Autocomplete.jsx
- components/Property/PropertySearch/Autocomplete/Autocomplete.module.css
- components/Property/PropertySearch/Autocomplete/Autocomplete.stories.jsx
- components/Property/PropertySearch/Autocomplete/Autocomplete.test.jsx
- components/Property/PropertySearch/PropertySearch.jsx
- components/Property/PropertyTitleDetails/PropertyTitleDetails.module.css
https://deloittedigital.atlassian.net/browse/BVPS-167
> BVPS-167 Autocomplete

- components/Property/PropertySearch/Autocomplete/Autocomplete.jsx
Trying to debug test that is not failing locally but failing pipeline...
> Debugging Failing Pipeline

- components/Property/PropertyDetails/PropertyDetails.jsx
- components/Property/PropertyOwner/PropertyOwner.jsx
- components/Property/PropertyTitleDetails/PropertyTitleDetails.jsx
- components/Property/RegeneratePINModal/RegeneratePINModal.jsx
https://deloittedigital.atlassian.net/browse/BVPS-292
> Adding in GCNotify functionality for regenerate PIN API

- components/Button/Button.module.css
- components/Button/Button.stories.jsx
- components/Button/index.jsx
[BVPS-308](https://deloittedigital.atlassian.net/browse/BVPS-308)
Button style for access request page, including dark background and danger button
> Bvps 308 danger button

- components/Property/ExpirePINModal/ExpirePINModal.jsx
- components/Property/ExpirePINModal/ExpirePINModal.module.css
- components/Property/PropertyOwner/PropertyOwner.jsx
[BVPS-309](https://deloittedigital.atlassian.net/browse/BVPS-309)
Add email and phone to expire pin modal
> add email and phone to expire pin modal

- assets/content/content.json
- components/Footer/index.jsx
- components/Header/Header.jsx
- components/Header/Header.module.css
- components/Search Results/SearchResults.jsx
- components/Search Results/SearchResults.test.jsx
[BVPS-319](https://deloittedigital.atlassian.net/browse/BVPS-319): help button redirect
[BVPS-320](https://deloittedigital.atlassian.net/browse/BVPS-320): home page language change
[BVPS-322](https://deloittedigital.atlassian.net/browse/BVPS-322): Links at footer section
[BVPS-323](https://deloittedigital.atlassian.net/browse/BVPS-323): Enter 3 characters text change
[BVPS-328](https://deloittedigital.atlassian.net/browse/BVPS-328): Addresses found wording change
> bug fix: 319, 320, 322,323, 328

- assets/content/content.json
- components/Property/PropertyLayout/PropertyLayout.jsx
- components/Property/PropertyLayout/PropertyLayout.module.css
- components/Property/PropertySearch/Autocomplete/Autocomplete.jsx
- components/Property/PropertySearch/Autocomplete/Autocomplete.module.css
- components/Property/PropertySearch/PropertySearch.jsx
- components/Property/PropertySearch/PropertySearch.module.css
https://deloittedigital.atlassian.net/browse/BVPS-327
https://deloittedigital.atlassian.net/browse/BVPS-330
> Updating autocomplete search behaviour

- assets/content/content.json
- components/Property/PropertyDetails/PropertyDetails.jsx
- components/Property/PropertyDetails/PropertyDetails.module.css
https://deloittedigital.atlassian.net/browse/BVPS-325
- Attached screenshot of update view in comments of the bug ticket
- Text is: "No data available for the selected property."
> BVPS-325 No Data Return Case

- components/Property/PropertyLayout/PropertyLayout.jsx
- components/Property/PropertySearch/PropertySearch.jsx
- pages/home.js
- pages/property-search.js
https://deloittedigital.atlassian.net/browse/BVPS-334
- Adding in property-search route
> BVPS-334 Seperate Home and Property Pages

- components/Property/PropertySearch/PropertySearch.jsx
[BVPS-324](https://deloittedigital.atlassian.net/browse/BVPS-324)
Browser behaviour
> browser behaviour

- components/AccessManagement/GrantModal/GrantModal.jsx
- components/AccessManagement/RejectModal/RejectModal.jsx
https://deloittedigital.atlassian.net/browse/BVPS-296
https://deloittedigital.atlassian.net/browse/BVPS-295
> BVPS-295+296 - Updating Reject Modal and Grant Modal for GC Notify Functionality

- components/Property/ViewPINHistory/ViewPINHistory.jsx
- components/Property/ViewPINHistory/ViewPINHistory.module.css
- Making email icon and email string appear on same line
- Fixing type not showing up
> View PIN History Modal fixes

- components/Property/PropertyLayout/PropertyLayout.jsx
- components/Property/PropertySearch/Autocomplete/Autocomplete.jsx
- pages/home.js
https://deloittedigital.atlassian.net/browse/BVPS-347
> BVPS-347-Autocomplete-Issues-From-Home-Page

- components/Property/ViewPINHistory/ViewPINHistory.module.css
style change for audit log header - 1px smaller fits header in one row
> view PIN history table padding

- components/UserManagement/DeactivateModal/DeactivateModal.jsx
[BVPS-298 - GC Notify Deactivate User](https://deloittedigital.atlassian.net/browse/BVPS-298)
> BVPS-298 - GC Notify Deactivate User

- assets/svgs/CleanBCLogo.jsx
> logo svg fix

- components/Property/PropertyTitleDetails/PropertyTitleDetails.jsx
https://deloittedigital.atlassian.net/browse/BVPS-349
> BVPS-349 - Making UI the same for properties with single and multiple titles

- components/Property/ManagePINDropdown/ManagePINDropdown.jsx
- components/Property/PropertyOwner/PropertyOwner.jsx
- components/Property/PropertySearch/PropertySearch.module.css
- styles/globals.css
> More bug fixes

- components/Property/ManagePINDropdown/ManagePINDropdown.jsx
- components/Property/ManagePINDropdown/ManagePINDropdown.stories.jsx
- components/Property/ManagePINDropdown/ManagePINDropdown.test.jsx
- components/Property/PropertyDetails/PropertyDetails.jsx
- components/Property/PropertyLayout/PropertyLayout.jsx
- components/Property/PropertyOwner/PropertyOwner.jsx
- components/Property/PropertyTitleDetails/PropertyTitleDetails.jsx
https://deloittedigital.atlassian.net/browse/BVPS-371
- Updating manage PIN dropdown so that View PIN option on appears for Super Admins
> View PIN bug fix

- components/Property/ManagePINDropdown/ManagePINDropdown.jsx
- components/Property/ManagePINDropdown/ManagePINDropdown.stories.jsx
- components/Property/PropertyOwner/PropertyOwner.stories.jsx
- pages/property-search.js
Bug Fix: Make View PIN option in Manage PIN dropdown only visible to Super Admins
> View PIN bugfix

- assets/content/content.json
https://deloittedigital.atlassian.net/browse/BVPS-396
> BVPS-396 - Pluralization Content Bug Fix

- components/Address Card/AddressCard.module.css
- components/Header/Header.jsx
- components/Modal/Modal.jsx
- components/Modal/Modal.module.css
- components/Property/PropertyLayout/PropertyLayout.module.css
- components/RadioButton/RadioButton.jsx
- components/RadioButton/RadioButton.module.css
- components/Search Results/SearchResults.module.css
- styles/globals.css
https://deloittedigital.atlassian.net/browse/BVPS-392
> BVPS-392 Accessibility Fixes

- components/Property/PropertySearch/Autocomplete/Autocomplete.jsx
- components/Property/PropertySearch/PropertySearch.jsx
https://deloittedigital.atlassian.net/browse/BVPS-404
> BVPS-404 Autocomplete Bug Fix

- assets/content/content.json
- components/Modal/Modal.module.css
https://deloittedigital.atlassian.net/browse/BVPS-391
> BVPS-391 Deactivate User Popup

- components/Property/PropertyLayout/PropertyLayout.module.css
https://deloittedigital.atlassian.net/browse/BVPS-449
> BVPS 449 - Bug Fix: Layout expands when clicking on property search result

- components/Property/PropertyTitleDetails/PropertyTitleDetails.jsx
- components/Property/PropertyTitleDetails/PropertyTitleDetails.module.css
https://deloittedigital.atlassian.net/browse/BVPS-443
- Screenshots of FE added to Jira ticket
> BVPS-443 - Property Details Accordion

- assets/content/content.json
- components/Header/Header.jsx
- components/Property/PropertyOwner/PropertyOwner.module.css
- components/Property/RegeneratePINModal/RegeneratePINModal.jsx
- components/Property/ViewPINHistoryModal/ViewPINHistory/ViewPINHistory.test.jsx
- components/Textbox/Textbox.module.css
- styles/globals.css
https://deloittedigital.atlassian.net/browse/BVPS-467
- Content/Text Updates
https://deloittedigital.atlassian.net/browse/BVPS-470
- Removing Help Button
> BVPS-467 + BVPS-470

- assets/content/content.json
- components/Footer/Footer.module.css
- components/Header/Header.jsx
- components/Header/Header.module.css
https://deloittedigital.atlassian.net/browse/BVPS-469
- Screenshot added to ticket
> BVPS-469 Submit Support Ticket Button

- components/AccessManagement/AccessSearch/AccessSearch.module.css
- components/AccessManagement/CompletedRequests/CompletedRequests.module.css
- components/AccessManagement/PendingRequests/PendingRequests.module.css
- components/Modal/Modal.module.css
- components/UserManagement/ActiveUsers/ActiveUsers.module.css
- components/UserManagement/DeactivatedUsers/DeactivatedUsers.module.css
- components/UserManagement/EditModal/EditModal.module.css
- components/UserManagement/UserSearch/UserSearch.module.css
https://deloittedigital.atlassian.net/browse/BVPS-460
- BVPS-460: User Management tablet view fixes
https://deloittedigital.atlassian.net/browse/BVPS-461
- BVPS-461: Access Requests tablet view fixes
> Tablet View Fixes: User Management Page (BVPS-460) + Access Requests Page (BVPS-461)

- .env.template
- assets/content/content.json
- components/Header/Header.jsx
- components/PageBanner/PageBanner.module.css
- components/Property/PropertyLayout/PropertyLayout.test.jsx
- components/Property/PropertySearch/PropertySearch.jsx
- components/Property/PropertySearch/PropertySearch.module.css
- components/Property/PropertySearch/PropertySearch.test.jsx
- components/Property/PropertySearchHeader/PropertySearchHeader.module.css
- components/RequestAccess/RequestForm/RequestForm.module.css
https://deloittedigital.atlassian.net/browse/BVPS-463
- Tablet view fixes for Request Access page
- Also added in env variable for submit support ticket url
> BVPS-463 Tablet View Fixes - Request Access Page 

- assets/content/content.json
- components/Property/PropertySearch/Autocomplete/Autocomplete.jsx
- components/Property/PropertySearch/Autocomplete/Autocomplete.module.css
- components/Property/PropertySearch/Autocomplete/Autocomplete.test.jsx
- components/RequestAccess/RequestForm/RequestForm.jsx
- components/RequestAccess/RequestForm/RequestForm.module.css
https://deloittedigital.atlassian.net/browse/BVPS-428
- Screenshot of alert attached in Jira ticket
> BVPS-428: Adding request access alert message (+ fixing autocomplete styling bug)

- assets/content/content.json
- components/Property/PropertyDetails/PropertyDetails.jsx
- components/Property/PropertyOwner/PropertyOwner.jsx
- components/Property/PropertyOwner/PropertyOwner.module.css
- components/Property/PropertyTitleDetails/PropertyTitleDetails.jsx
Adding Incorporation Number to FE owner section for corporate properties.
- If property details API returns incorporation number, it is included in owner section, and "Full Name" text is switched to "Incorporation Name"
- Screenshots attached in Jira ticket: https://deloittedigital.atlassian.net/browse/BVPS-472
> BVPS-472 Incorporation Number

- components/Property/ExpirePINModal/ExpirePINModal.jsx
- components/Property/RegeneratePINModal/RegeneratePINModal.jsx
Fix for inefficient regular expression issues: https://github.com/bcgov/bc-emli-pin-mgmt-fe/security/code-scanning?query=is%3Aopen+branch%3Adev
> Email regex fix

- components/Header/Header.jsx
- pages/404.js
- Fix for "Back to homepage" button so that it directs user back to homepage as expected
- Fix for "Submit a Support Ticket" button so that it does not appear on 404 page
> Fixes to 404 page

- components/RequestAccess/RequestForm/RequestForm.jsx
Checks if there is a email coming from token
- If yes, email field is auto-populated and disabled
- If no, email field is empty and user can enter their email
> Updating request-access page email field

- pages/request-access.js
- services/authentication/userAuthService.js
If user already has an approved account, they will be redirected from the request-access page to the home page
> Updating request-access page routing

- assets/content/content.json
- components/UserManagement/UserSearch/UserSearch.jsx
- components/UserManagement/UsersList/UsersList.jsx
https://deloittedigital.atlassian.net/browse/BVPS-448
> BVPS-448 - Adding "Last updated at" column to deactivate user table

- assets/content/content.json
- components/Property/PropertyDetails/PropertyDetails.jsx
- components/Property/PropertyOwner/PropertyOwner.jsx
- components/Property/PropertyOwner/PropertyOwner.module.css
- components/Property/RegeneratePINModal/RegeneratePINModal.jsx
https://deloittedigital.atlassian.net/browse/BVPS-485
- Fixing casing of owner name and mailing address
- Updating error messages for regenerate PIN modal
> BVPS-485 - FE Fixes

- components/AccessManagement/AccessLayout/AccessLayout.jsx
- components/AccessManagement/AccessList/AccessList.jsx
- components/AccessManagement/PendingRequests/PendingRequests.jsx
- components/Table/Table.jsx
- components/UserManagement/ActiveUsers/ActiveUsers.jsx
- components/UserManagement/EditModal/EditModal.jsx
- components/UserManagement/UserManagementLayout/UserManagementLayout.jsx
- components/UserManagement/UserUpdate/UserUpdate.jsx
- pages/access-request.js
- pages/user-management.js
Updating FE such that:
1. Admins cannot approve access requests for super admins
2. Admins cannot update users to grant super admin permissions
https://deloittedigital.atlassian.net/browse/BVPS-494
> BVPS-494 Stopping admins from approving/editing users to super admin

- components/DashboardLayout/DashboardLayout.jsx
- components/DashboardLayout/DashboardLayout.module.css
https://deloittedigital.atlassian.net/browse/BVPS-495
> BVPS-495 Updating Metabase dashboard size and adding loading icon

- CSSStub.js
- components/Alert/Alert.test.jsx
- components/Button/Button.stories.jsx
- components/Button/Button.test.jsx
- components/CheckBox/CheckBox.jsx
- components/CheckBox/CheckBox.test.jsx
- components/CheckBox/checkbox.stories.jsx
- components/DashboardLayout/DashboardLayout.module.css
- components/DashboardLayout/DashboardLayout.stories.jsx
- components/DashboardLayout/DashboardLayout.test.jsx
- components/TabGroup/TabGroup.stories.jsx
- components/TabGroup/TabGroup.test.jsx
- components/Table/Table.stories.jsx
- components/Table/Table.test.jsx
- jest.config.js
Adding in unit tests for the following components (all above 80% coverage):
- [BVPS-498](https://deloittedigital.atlassian.net/browse/BVPS-498) - Alert Component
- [BVPS-499](https://deloittedigital.atlassian.net/browse/BVPS-499) - Button Component
- [BVPS-500](https://deloittedigital.atlassian.net/browse/BVPS-500) - CheckBox Component
- [BVPS-501](https://deloittedigital.atlassian.net/browse/BVPS-501) - DashboardLayout Component
- [BVPS-508](https://deloittedigital.atlassian.net/browse/BVPS-508) - TabGroup Component
- [BVPS-504](https://deloittedigital.atlassian.net/browse/BVPS-504) - Table Component
Also adding in padding to top of Metabase dashboard.
> BVPS-496 FE Unit Tests - Part 1

- components/Property/PropertyDetails/PropertyDetails.jsx
Fix to ensure that proper message is displayed in the event of an error (instead of blank grey box for property details section)
> Property details bug fix

- components/AccessManagement/AccessSearch/AccessSearch.jsx
- components/UserManagement/UserSearch/UserSearch.jsx
Fixing the following issue:
Search bar issue - deleting text without clicking X leaves page stuck in search state
> fixing search bar issue

- __tests__/pages/home.test.js
- components/Address Card/AddressCard.jsx
- components/Address Card/AddressCard.test.jsx
- components/Button/index.jsx
- components/Dropdown/Dropdown.jsx
- components/Dropdown/Dropdown.module.css
- components/Modal/Modal.jsx
- components/Property/ManagePINDropdown/ManagePINDropdown.jsx
- components/Property/ManagePINDropdown/ManagePINDropdown.test.jsx
- components/Property/Property.test.jsx
- components/Property/PropertyDetails/PropertyDetails.jsx
- components/Property/PropertyDetails/PropertyDetails.test.jsx
- components/Property/PropertyLayout/PropertyLayout.jsx
- components/Property/PropertyLayout/PropertyLayout.test.jsx
- components/Property/PropertyOwner/PropertyOwner.jsx
- components/Property/PropertyOwner/PropertyOwner.test.jsx
- components/Property/PropertySearch/Autocomplete/Autocomplete.jsx
- components/Property/PropertySearch/Autocomplete/Autocomplete.test.jsx
- components/Property/PropertySearch/PropertySearch.jsx
- components/Property/PropertySearch/PropertySearch.test.jsx
- components/Property/PropertyTitleDetails/PropertyTitleDetails.jsx
- components/Property/PropertyTitleDetails/PropertyTitleDetails.test.jsx
- components/Property/RegeneratePINModal/RegeneratePINModal.jsx
- components/Property/RegeneratePINModal/RegeneratePINModal.test.jsx
- components/Search Results/SearchResults.jsx
- components/Search Results/SearchResults.test.jsx
- pages/home.js
- pages/property-search.js
- public/snowplow.js
Adding in the custom tracking from this table: https://deloittedigital.atlassian.net/wiki/spaces/BVPS/pages/3184558200/Analytics+Tracking
> Adding in Snowplow custom tracking

- components/Property/PropertySearch/Autocomplete/Autocomplete.jsx
- components/Property/RegeneratePINModal/RegeneratePINModal.jsx
- Autocomplete Bug- Now using address field instead of search
- Regenerate pin calling twice snowplow event twice - Now fixed to single call
> Snowplow Fixes

- assets/content/content.json
- components/UserManagement/EditModal/EditModal.jsx
Screenshots added in Jira ticket: https://deloittedigital.atlassian.net/jira/software/projects/BVPS/boards/535/backlog?selectedIssue=BVPS-521
> BVPS-521 Adding Edit User confirmation modal and BVPS-518 system name update

- README.md
- assets/content/content.json
- components/AccessManagement/AccessForm/AccessForm.jsx
- components/AccessManagement/GrantModal/GrantModal.jsx
- components/AccessManagement/GrantModal/GrantModal.module.css
- components/AccessManagement/RejectModal/RejectModal.jsx
- components/AccessManagement/RejectModal/RejectModal.module.css
- components/UserManagement/DeactivateModal/DeactivateModal.jsx
- components/UserManagement/DeactivateModal/DeactivateModal.module.css
- components/UserManagement/EditModal/EditModal.jsx
- Deactivate User Confirmation Modal: https://deloittedigital.atlassian.net/browse/BVPS-525
- Grant Request Confirmation Modal: https://deloittedigital.atlassian.net/browse/BVPS-528
- Reject Request Confirmation Modal: https://deloittedigital.atlassian.net/browse/BVPS-531
> Adding in confirmation modals for deactivate user, grant access, and reject access.

- assets/content/content.json
- components/AccessManagement/AccessLayout/AccessLayout.jsx
- components/AccessManagement/GrantModal/GrantModal.jsx
- components/AccessManagement/GrantModal/GrantModal.module.css
- components/AccessManagement/RejectModal/RejectModal.jsx
- components/AccessManagement/RejectModal/RejectModal.module.css
- components/UserManagement/DeactivateModal/DeactivateModal.jsx
- components/UserManagement/DeactivateModal/DeactivateModal.module.css
- components/UserManagement/EditModal/EditModal.jsx
- components/UserManagement/EditModal/EditModal.module.css
- components/UserManagement/UserManagementLayout/UserManagementLayout.jsx
- Edit User Toaster: https://deloittedigital.atlassian.net/browse/BVPS-522
- Deactivate User Toaster: https://deloittedigital.atlassian.net/browse/BVPS-526
- Grant Request Toaster: https://deloittedigital.atlassian.net/browse/BVPS-529
- Reject Request Toaster: https://deloittedigital.atlassian.net/browse/BVPS-532
- Access Code Regeneration Popup: https://deloittedigital.atlassian.net/browse/BVPS-537
> Toaster success / failure notifications

- components/AccessManagement/AccessSearch/AccessSearch.jsx
- components/Table/Table.jsx
- components/Table/Table.module.css
- components/UserManagement/UserSearch/UserSearch.jsx
Sorting Icon: https://deloittedigital.atlassian.net/browse/BVPS-519
Updating search functionality: https://deloittedigital.atlassian.net/browse/BVPS-520
> Table changes

- assets/content/content.json
- components/AccessManagement/AccessList/AccessList.jsx
- components/AccessManagement/GrantModal/GrantModal.jsx
- components/RequestAccess/RequestForm/RequestForm.test.jsx
- components/UserManagement/ActiveUsers/ActiveUsers.module.css
- components/UserManagement/DeactivateModal/DeactivateModal.jsx
- components/UserManagement/EditModal/EditModal.jsx
- components/UserManagement/UsersList/UsersList.jsx
- BVPS-518 - Update Tool Name: https://deloittedigital.atlassian.net/browse/BVPS-518
- BVPS-521 - Edit User Confirmation Dialogue: https://deloittedigital.atlassian.net/browse/BVPS-521
- BVPS-522 - Edit User Success/Failure Toaster: https://deloittedigital.atlassian.net/browse/BVPS-522
- BVPS-526 - Deactivate User Success/Failure Toaster: https://deloittedigital.atlassian.net/browse/BVPS-526
- BVPS-528 - Grant Request Confirmation Dialogue: https://deloittedigital.atlassian.net/browse/BVPS-528
- BVPS-534 - Organization Field: https://deloittedigital.atlassian.net/browse/BVPS-534
- BVPS-535 - Identity Type: https://deloittedigital.atlassian.net/browse/BVPS-535
> Content updates

- assets/content/content.json
- components/AccessManagement/AccessList/AccessList.jsx
- components/AccessManagement/RejectModal/RejectModal.jsx
- components/UserManagement/DeactivateModal/DeactivateModal.jsx
- components/UserManagement/UsersList/UsersList.jsx
- BVPS-524 (Edit user add to table)
- BVPS-527/541 (Deactivate History add to table)
- BVPS-533 (Access Request Table - Time of approval)
- BVPS-540 (Multi unit housing error message)
- Deactivate multiple users
> Adding fields to tables
